Migrate vm
openvcloud/openvcloud pull request #48
Opened 2017-10-11 15:09 UTC by khaledkbadr

2017-10-11 15:21 UTC, rkhamis approved these changes

2017-10-15 11:17 UTC, abdulrahmantkhalifa requested changes

2017-10-15 11:17 UTC, abdulrahmantkhalifa commented on actors/cloudbroker/cloudbroker__computenode/methodclass/cloudbroker_computenode.py
> +        if vmaction not in ('move', 'stop', 'migrate'):
how is this different from move, ( i understand this is for the demo but it should not be on master )

2017-10-24 12:02 UTC, grimpy requested changes
Please only keep move or migrate and add a flag force from within the actions popup. Explain clearly in the warning message

2017-10-25 06:56 UTC, khaledkbadr commented
I moved @grimpy comment to https://github.com/openvcloud/openvcloud/pull/59

2017-10-25 06:56 UTC, closed without merging