1.1.0 beta 0 changes
openvcloud/openvcloud pull request #59
Opened 2017-10-24 11:27 UTC by rkhamis

2017-10-25 06:55 UTC, khaledkbadr requested changes

2017-10-25 06:55 UTC, khaledkbadr commented on actors/cloudbroker/cloudbroker__computenode/methodclass/cloudbroker_computenode.py
> +        if vmaction not in ('move', 'stop', 'migrate'):
Please only keep move or migrate and add a flag force from within the actions popup. Explain clearly in the warning message

2017-10-26 07:56 UTC, khaledkbadr submitted a review, later dismissed

2017-10-26 08:51 UTC, grimpy requested changes

2017-10-26 08:51 UTC, grimpy commented on actors/cloudbroker/cloudbroker__computenode/methodclass/cloudbroker_computenode.py
> +        force = bool(int(force))
you shouldnt have to do this atleast if you define force in the actor.spec properly

2017-10-26 09:56 UTC, grimpy approved these changes

2017-10-26 09:58 UTC, merged